server:
    port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "1.0"

accounts:
  message: Hi! I am Accounts Service
  contactDetails:
    name: "Bibek"
    email: "bibek@gmail.com"
  onCallSupport:
    -(555) 555-1234