spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
#            search-locations: file:/config
        git:
          uri: "https://github.com/BibekRegmi9/neo-bank-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071